makecode:
  target: microbit
  platform: microbit
  home_url: https://makecode.microbit.org/
theme: jekyll-theme-midnight
asignatura: Aprendizaje y enseñanza de la Tecnología
Cosas: 
  - cosas
  - cosas
include:
  - assets
  - README.md
